=== CIMAC-CIDC/cidc-schemas/cidc_schemas/metaschema/strict_meta_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strict_meta_schema",
  "title": "Strict meta-schema",
  "type": ["object", "boolean"],
  "oneOf": [
    { "required": ["$ref"] },
    { "required": ["const"] },
    {
      "not": {
        "$comment": "this makes additionalProperties or inheritableBase required only for object-describing schemas",
        "anyOf": [
          {
            "properties": {
              "type": {
                "const": "object"
              }
            }
          },
          { "required": ["properties"] }
        ]
      }
    },
    {
      "type": "object",
      "required": ["additionalProperties"],
      "not": {
        "required": ["inheritableBase"],
        "$comment": "'not' disallows matching this, making additionalProperties and inheritableBase mutually exclusive"
      }
    },
    {
      "type": "object",
      "not": {
        "required": ["additionalProperties"],
        "$comment": "'not' disallows matching this, making additionalProperties and inheritableBase mutually exclusive"
      },
      "required": ["inheritableBase"]
    }
  ],
  "properties": {
    "additionalProperties": {
      "$comment": "overrides draft-07 definition",
      "enum": [
          false,
          true
      ]
    },
    "inheritableBase": {
      "$comment": "Shows that a schema is an extensible 'abstract base' to inherit from and doesn't have `additionalProperties` set to false. No end user objects should be of that schema, only of something 'descendant' from it.",
      "const": true
    },
    "example": {
      "type": "string"
    },
    "in_doc_ref_pattern": {
      "$comment": "used in prism custom validator for in doc refs integrity",
      "type": "string"
    },

    "mergeStrategy": { "$comment": "jsonmerge specific" },
    "mergeOptions": { "$comment": "jsonmerge specific" },

    "$schema": {
      "$comment": "overrides draft-07 definition to point to this strict schema",
      "const": "metaschema/strict_meta_schema.json#"
    },
    "additionalItems": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "$ref": "#"
    },
    "items": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "$ref": "#"
    },
    "definitions": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": { "$ref": "#" }
    },
    "properties": {
      "type": "object",
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": { "$ref": "#" }
    },
    "patternProperties": false,
    "dependencies": {
      "type": "object",
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": {
        "anyOf": [
          { "$ref": "#" },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },

    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": true,
    "readOnly": {
      "type": "boolean",
      "default": false
    },
    "examples": {
      "type": "array",
      "items": true
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minLength": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "maxItems": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minItems": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "contains": { "$ref": "#" },
    "maxProperties": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minProperties": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "propertyNames": { "$ref": "#" },
    "const": true,
    "enum": {
      "type": "array",
      "items": true
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "encrypt": {
      "type": "boolean",
      "default": false
    },
    "format": { "type": "string" },
    "contentMediaType": { "type": "string" },
    "contentEncoding": { "type": "string" },

    "if": { "$ref": "#" },
    "then": { "$ref": "http://json-schema.org/draft-07/schema#" },
    "else": { "$ref": "#" },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": { "$ref": "#" }
  },
  "definitions": {
    "schemaArray": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "type": "array",
      "minItems": 1,
      "items": {
        "anyOf": [
          {"$ref": "#"},
          {"$ref": "http://json-schema.org/draft-07/schema#"}
        ]
      }
    },
    "stringArray": {
      "type": "array",
      "items": { "type": "string" }
    },
    "simpleTypes": { "$ref": "http://json-schema.org/draft-07/schema#/definitions/simpleTypes" }
  },
  "additionalProperties": false
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/nanostring_assay.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "nanostring_assay",
  "title": "Nanostring Assay",
  "type": "object",
  "description": "A microarray assay for expression levels, suitable for smaller samples than RNA-seq",
  "additionalProperties": false,
  "mergeStrategy": "objectMerge",
  "definitions": {
    "run": {
      "type": "object",
      "description": "A single Nanostring run.",
      "additionalProperties": false,
      "required": ["run_id", "samples"],
      "properties": {
        "run_id": {
          "type": "string",
          "description": "A unique ID that separates the different runs of the given same sample."
        },
        "samples": {
          "type": "array",
          "mergeStrategy": "arrayMergeById",
          "mergeOptions": {
            "idRef": "cimac_id"
          },
          "items": {"$ref":"assays/nanostring_assay.json#definitions/sample"}
        },
        "control_raw_rcc": {
          "$ref": "artifacts/artifact_rcc.json",
          "$comment": "The RCC data file for a reference RNA sample"
        }
      }
    },

    "sample": {
      "type": "object",
      "description": "A data record for a single sample from a single Nanostring run.",
      "additionalProperties": false,
      "required": ["cimac_id", "raw_rcc"],
      "properties": {
        "cimac_id": {
            "$comment": "Id of a sample within this clinical trial, that this assay record is based upon.",
            "$ref": "sample.json#properties/cimac_id"
        },
        "raw_rcc": {
          "$ref": "artifacts/artifact_rcc.json",
          "$comment": "The RCC data file generated by Nanostring for the given sample in the given run."
        }
      }
    }
  },

  "properties": {
    "assay_creator": {
      "$ref": "assays/components/assay_core.json#properties/assay_creator"
    },
    "batch_id": {
      "type": "string",
      "description": "A unique ID that separates the different batches of Nanostring."
    },
    "data": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "normalized": {
          "$ref": "artifacts/artifact_csv.json"
        },
        "raw": {
          "$ref": "artifacts/artifact_csv.json"
        }
      }
    },
    "runs": {
      "type": "array",
      "mergeStrategy": "arrayMergeById",
      "mergeOptions": {
        "idRef": "/run_id"
      },
      "items": { "$ref": "assays/nanostring_assay.json#definitions/run" }
    }
  },
  "required": ["data", "runs"]
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/rna/fusion.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "fusion",
    "title": "RNAseq Fusion Output Files",
    "type": "object",
    "description": "Fusion output sample files.",
    "properties": {
      "fusion_predictions": {
        "$ref": "artifacts/artifact_tsv.json"
      }
    },
    "required": [
      "fusion_predictions"
    ],
    "additionalProperties": false
  }

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/imaging/mif_roi.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "mif_roi",
  "description": "A region of interest (ROI) is a portion of an image which has been analyzed using image processing software.",
  "allOf": [
    { "$ref": "assays/components/mapping.json" },
    { "$ref": "assays/components/composite_image.json" }
  ],
  "additionalProperties": false,
  "properties": {
    "roi_id": {
        "description": "Identifier of a region of interest within one mIF slide, e.g. 1, 2, 3 or [123 x 321]",
        "type": "string"
    },

    "binary_seg_maps": {"$ref": "assays/components/mapping.json#properties/binary_seg_maps" },
    "cell_seg_data": {"$ref": "assays/components/mapping.json#properties/cell_seg_data" },
    "cell_seg_data_summary": {"$ref": "assays/components/mapping.json#properties/cell_seg_data_summary" },
    "phenotype_map": {"$ref": "assays/components/mapping.json#properties/phenotype_map" },
    "score_data": {"$ref": "assays/components/mapping.json#properties/score_data" },

    "im3": {"$ref": "assays/components/composite_image.json#properties/im3"},
    "composite_image": {"$ref": "assays/components/composite_image.json#properties/composite_image"},
    "component_data": {"$ref": "assays/components/composite_image.json#properties/component_data"}
  },
  "mergeStrategy": "objectMerge",
  "required": [
    "binary_seg_maps",
    "cell_seg_data",
    "cell_seg_data_summary",
    "phenotype_map",
    "score_data",
    "im3",
    "composite_image",
    "component_data"
  ]
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/rna/star.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "star",
  "title": "RNAseq Star Output Files",
  "type": "object",
  "description": "Star output sample files.",
  "properties": {
    "chimeric_out_junction": {
      "$ref": "artifacts/artifact_text.json"
    },
    "log_final_out": {
      "$ref": "artifacts/artifact_text.json"
    },
    "counts_tab": {
      "$ref": "artifacts/artifact_text.json"
    },
    "sorted_bam": {
      "$ref": "artifacts/artifact_bam.json"
    },
    "sorted_bam_index": {
      "$ref": "artifacts/artifact_bam_bai.json"
    },
    "sorted_bam_stat_txt": {
      "$ref": "artifacts/artifact_text.json"
    },
    "transcriptome_bam": {
      "$ref": "artifacts/artifact_bam.json"
    },
    "unsorted_bam": {
      "$ref": "artifacts/artifact_bam.json"
    },
    "log_out": {
      "$ref": "artifacts/artifact_text.json"
    },
    "log_progress_out": {
      "$ref": "artifacts/artifact_text.json"
    },
    "sj_out_tab": {
      "$ref": "artifacts/artifact_text.json"
    },
    "star_genome_sjdb_info_txt": {
      "$ref": "artifacts/artifact_text.json"
    },
    "star_genome_sjdb_list_out_tab": {
      "$ref": "artifacts/artifact_text.json"
    },
    "star_pass1_log_final_out": {
      "$ref": "artifacts/artifact_text.json"
    },
    "star_pass1_sj_out_tab": {
      "$ref": "artifacts/artifact_text.json"
    },
    "downsampling_bam": {
      "$ref": "artifacts/artifact_bam.json"
    },
    "downsampling_bam_index": {
      "$ref": "artifacts/artifact_bam_bai.json"
    }
  },
  "required": [
    "chimeric_out_junction",
    "log_final_out",
    "counts_tab",
    "sorted_bam",
    "sorted_bam_index",
    "sorted_bam_stat_txt",
    "transcriptome_bam",
    "unsorted_bam",
    "log_out",
    "log_progress_out",
    "sj_out_tab",
    "star_genome_sjdb_info_txt",
    "star_genome_sjdb_list_out_tab",
    "star_pass1_log_final_out",
    "star_pass1_sj_out_tab",
    "downsampling_bam",
    "downsampling_bam_index"
  ],
  "additionalProperties": false
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/wes/copynumber.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "copynumber",
  "title": "WES Copynumber Output Files",
  "type": "object",
  "description": "Copy number output files.",
  "properties": {
    "copynumber_cnv_calls": {
      "$ref": "artifacts/artifact_text.json"
    },
    "copynumber_cnv_calls_tsv": {
      "$ref": "artifacts/artifact_tsv.json"
    }
  },
  "required": [
    "copynumber_cnv_calls",
    "copynumber_cnv_calls_tsv"
  ],
  "additionalProperties": false
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/rna/rna_entry.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "rna_entry",
  "title": "RNAseq assay record",
  "type": "object",
  "description": "A single data record from RNAseq assay.",
  "additionalProperties": false,
  "allOf": [
    { "$ref": "assays/components/ngs/ngs_assay_record.json" }
  ],
  "properties": {
    "library_yield_ng": {
      "description": "Resulting yield (in ng) from library construction.",
      "type": "number"
    },
    "dv200": {
      "description": "The percentage of fragments > 200 nucleotides.",
      "type": "number",
      "minimum": 0,
      "maximum": 1
    },
    "rqs": {
      "description": "RNA quality score. (0-10)",
      "type": "number",
      "minimum": 0,
      "maximum": 10
    },
    "rin": {
      "description": "RNA integrity number. (0-10)",
      "type": "number",
      "minimum": 0,
      "maximum": 10
    },
    "quality_flag": {
      "description": "Flag used for quality.",
      "type": "number"
    },
    "cimac_id": {"$ref": "assays/components/ngs/ngs_assay_record.json#properties/cimac_id"},
    "files": {"$ref": "assays/components/ngs/ngs_assay_record.json#properties/files"}
  },
  "mergeStrategy": "objectMerge"
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/imaging/mif_export.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "mif_export",
  "description": "An analysis export from inForm of a region of interest (ROI).",
  "allOf": [
    { "$ref": "assays/components/mapping.json" }
  ],
  "mergeStrategy": "objectMerge",
  "mergeOptions": {"idRef": "/export_id"},
  "additionalProperties": false,
  "properties": {
      "export_id": {
        "description": "Name used for an inForm export of a region of interest within one mIF slide, e.g. CD8, CD45RO",
        "type": "string"
      },

      "cell_seg_data": {"$ref": "assays/components/mapping.json#properties/cell_seg_data" },
      "cell_seg_data_summary": {"$ref": "assays/components/mapping.json#properties/cell_seg_data_summary" },
      "phenotype_map": {"$ref": "assays/components/mapping.json#properties/phenotype_map" },
      "score_data": {"$ref": "assays/components/mapping.json#properties/score_data" },
      "tissue_seg_data": {"$ref": "assays/components/mapping.json#properties/tissue_seg_data" },
      "tissue_seg_data_summary": {"$ref": "assays/components/mapping.json#properties/tissue_seg_data_summary" },
      "binary_seg_maps": {"$ref": "assays/components/mapping.json#properties/binary_seg_maps" },

      "image_with_all_seg": {"$ref": "assays/components/mapping.json#properties/seg_maps" },
      "image_with_cell_seg_map": {"$ref": "assays/components/mapping.json#properties/seg_maps" },
      "image_with_phenotype_map": {"$ref": "assays/components/mapping.json#properties/phenotype_map" },
      "image_with_tissue_seg": {"$ref": "assays/components/mapping.json#properties/seg_maps" }
  },
  "required": [
      "export_id",
      "cell_seg_data",
      "cell_seg_data_summary"
  ]
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/controls.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "control",
    "title": "Control",
    "description": "Common information about the controls used in a number of immune-oncology assays.",
    "inheritableBase": true,
    "type": "object",
    "properties": {
        "control_name": {
            "description": "Name or identifier of a control sample.",
            "type": "string"
        }
    },
    "required": ["control_name"]
  }
