=== CIMAC-CIDC/cidc-schemas/cidc_schemas/metaschema/strict_meta_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strict_meta_schema",
  "title": "Strict meta-schema",
  "type": ["object", "boolean"],
  "oneOf": [
    { "required": ["$ref"] },
    { "required": ["const"] },
    {
      "not": {
        "$comment": "this makes additionalProperties or inheritableBase required only for object-describing schemas",
        "anyOf": [
          {
            "properties": {
              "type": {
                "const": "object"
              }
            }
          },
          { "required": ["properties"] }
        ]
      }
    },
    {
      "type": "object",
      "required": ["additionalProperties"],
      "not": {
        "required": ["inheritableBase"],
        "$comment": "'not' disallows matching this, making additionalProperties and inheritableBase mutually exclusive"
      }
    },
    {
      "type": "object",
      "not": {
        "required": ["additionalProperties"],
        "$comment": "'not' disallows matching this, making additionalProperties and inheritableBase mutually exclusive"
      },
      "required": ["inheritableBase"]
    }
  ],
  "properties": {
    "additionalProperties": {
      "$comment": "overrides draft-07 definition",
      "enum": [
          false,
          true
      ]
    },
    "inheritableBase": {
      "$comment": "Shows that a schema is an extensible 'abstract base' to inherit from and doesn't have `additionalProperties` set to false. No end user objects should be of that schema, only of something 'descendant' from it.",
      "const": true
    },
    "example": {
      "type": "string"
    },
    "in_doc_ref_pattern": {
      "$comment": "used in prism custom validator for in doc refs integrity",
      "type": "string"
    },

    "mergeStrategy": { "$comment": "jsonmerge specific" },
    "mergeOptions": { "$comment": "jsonmerge specific" },

    "$schema": {
      "$comment": "overrides draft-07 definition to point to this strict schema",
      "const": "metaschema/strict_meta_schema.json#"
    },
    "additionalItems": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "$ref": "#"
    },
    "items": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "$ref": "#"
    },
    "definitions": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": { "$ref": "#" }
    },
    "properties": {
      "type": "object",
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": { "$ref": "#" }
    },
    "patternProperties": false,
    "dependencies": {
      "type": "object",
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": {
        "anyOf": [
          { "$ref": "#" },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },

    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": true,
    "readOnly": {
      "type": "boolean",
      "default": false
    },
    "examples": {
      "type": "array",
      "items": true
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minLength": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "maxItems": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minItems": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "contains": { "$ref": "#" },
    "maxProperties": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minProperties": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "propertyNames": { "$ref": "#" },
    "const": true,
    "enum": {
      "type": "array",
      "items": true
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "encrypt": {
      "type": "boolean",
      "default": false
    },
    "format": { "type": "string" },
    "contentMediaType": { "type": "string" },
    "contentEncoding": { "type": "string" },

    "if": { "$ref": "#" },
    "then": { "$ref": "http://json-schema.org/draft-07/schema#" },
    "else": { "$ref": "#" },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": { "$ref": "#" }
  },
  "definitions": {
    "schemaArray": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "type": "array",
      "minItems": 1,
      "items": {
        "anyOf": [
          {"$ref": "#"},
          {"$ref": "http://json-schema.org/draft-07/schema#"}
        ]
      }
    },
    "stringArray": {
      "type": "array",
      "items": { "type": "string" }
    },
    "simpleTypes": { "$ref": "http://json-schema.org/draft-07/schema#/definitions/simpleTypes" }
  },
  "additionalProperties": false
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/rna/rnaseq_analysis.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "rnaseq_analysis",
  "title": "RNAseq analysis combined files",
  "type": "object",
  "description": "Combined analysis files for the whole RNAseq assay.",
  "additionalProperties": false,
  "properties": {
    "level_1": {
      "type": "array",
      "items": {
        "$ref": "assays/components/ngs/rna/rnaseq_level1_analysis.json"
      },
      "mergeStrategy": "arrayMergeById",
      "mergeOptions": {
        "idRef": "/cimac_id"
      }
    }
  }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/collection_event.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "collection_event.json",
  "description": "Defines a collection event and its biospecimen type hierarchy.",
  "additionalProperties": false,
  "type": "object",
  "definitions": {
    "specimen_type": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "specimen_type": {
          "$comment": "The name of this specimen type",
          "type": "string"
        },
        "derivatives": {
          "$comment": "The derivate specimen types for this specimen type (e.g., plasma is derived from whole blood).",
          "type": "array",
          "items": { "$ref": "#/definitions/specimen_type" }
        },
        "intended_assays": {
          "$comment": "The assay(s) with which this biospecimen will be analyzed.",
          "type": "array",
          "items": { "type": "string" }
        },
        "comments": { "type": "string" }
      },
      "required": ["specimen_type"]
    }
  },
  "properties": {
    "event_name": {
      "$comment": "The name of this collection event",
      "type": "string"
    },
    "specimen_types": {
      "$comment": "The array of root specimen types associated with this collection event",
      "type": "array",
      "items": { "$ref": "#/definitions/specimen_type" }
    }
  }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/mif-version_0.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "mif-v0",
  "title": "mIF Assay",
  "type": "object",
  "description": "Multiplex immunofluorescence.",
  "allOf": [
    { "$ref": "assays/components/assay_core.json" },
    { "$ref": "assays/components/image.json" },
    { "$ref": "assays/components/imaging_data.json" }
  ],
  "required": ["records", "panel", "antibodies"],
  "additionalProperties": false,
  "properties": {
    "assay_creator": { "$ref": "assays/components/assay_core.json#properties/assay_creator" },
    "slide_scanner_model": { "$ref": "assays/components/image.json#properties/slide_scanner_model" },
    "image_analysis_software": { "$ref": "assays/components/image.json#properties/image_analysis_software" },
    "image_analysis_software_version": { "$ref": "assays/components/image.json#properties/image_analysis_software_version" },
    "cell_segmentation_model": { "$ref": "assays/components/image.json#properties/cell_segmentation_model" },
    "positive_cell_detection": { "$ref": "assays/components/image.json#properties/positive_cell_detection" },
    "staining": { "$ref": "assays/components/imaging_data.json#properties/staining" },
    "staining_date": { "$ref": "assays/components/imaging_data.json#properties/staining_date" },
    "imaging_date": { "$ref": "assays/components/imaging_data.json#properties/imaging_date" },
    "imaging_status": { "$ref": "assays/components/imaging_data.json#properties/imaging_status" },

    "panel": {
        "type": "string",
        "enum": [
            "Panel 1: PD-L1, CD68, PD-1, CD8, CD3, pan-cytokeratin, DAPI",
            "Panel 2: FOXP3, Granzyme B, CD45RO, CD8, CD3, pan-cytokeratin, DAPI",
            "Panel 3: pan-cytokeratin, CD8, PD-1, PD-L1, DAPI",
            "Panel 4: SOX10, CD8, PD-1, PD-L1, DAPI"
        ]
    },

    "antibodies": {
      "type": "array",
      "mergeStrategy": "arrayMergeById",
      "mergeOptions": { "idRef": "antibody" },
      "items": {
        "description": "Data specific to antibody preparation on the multiplex immunofluorescence platform.",
        "type": "object",
        "allOf": [
          { "$ref": "assays/components/antibody.json" }
        ],
        "required": [
          "fluor_wavelength",
          "primary_ab_dilution",
          "dilutent",
          "fluor_dilution",
          "antigen_retrieval_time",
          "primary_incubation_time",
          "amplification_time"
        ],
        "additionalProperties": false,
        "properties": {
          "antibody": { "$ref": "assays/components/antibody.json#properties/antibody" },
          "clone": { "$ref": "assays/components/antibody.json#properties/clone" },
          "company": { "$ref": "assays/components/antibody.json#properties/company" },
          "cat_num": { "$ref": "assays/components/antibody.json#properties/cat_num" },
          "lot_num": { "$ref": "assays/components/antibody.json#properties/lot_num" },

          "export_name": {
            "description": "Name of this antibody in InForm export, e.g. 'CD8 (Opal 520)'",
            "type": "string"
          },
          "staining_order": {
            "description": "Order of staining applied",
            "type": "integer"
          },
          "fluor_wavelength": {
            "description": "Wavelength registered for Alexa Fluor processing.",
            "type": "integer"
          },
          "primary_ab_dilution": {
            "description": "Concentration ratio for primary antibody dilution.",
            "type": "string"
          },
          "dilutent": {
            "description": "Dilution agent used for antibody sample.",
            "type": "string"
          },
          "fluor_dilution":{
            "description": "Concentration ratio for fluor dilution agent.",
            "type": "string"
          },
          "antigen_retrieval_time": {
            "description": "Length of time needed for antigen retrieval.",
            "type": "string",
            "format": "time"
          },
          "primary_incubation_time": {
            "description": "Length of time for primary antibody incubation.",
            "type": "string",
            "format": "time"
          },
          "amplification_time": {
            "description": "Length of time required for amplified signal detection.",
            "type": "string",
            "format": "time"
          }
        }
      }
    },

    "records": {
      "type": "array",
      "description": "A single data record from mIF assay.",
      "mergeStrategy": "arrayMergeById",
      "mergeOptions": { "idRef": "cimac_id" },

      "items": {
        "type": "object",
        "description": "A single data record from mIF assay.",
        "required": ["cimac_id", "files"],
        "additionalProperties": false,
        "properties": {
          "cimac_id": {
            "$comment": "Id of an sample within this clinical trial, that this assay record is based upon.",
            "$ref": "sample.json#properties/cimac_id"
          },
          "files": {
            "type": "object",
            "description": "mIF assay input files.",
            "required": ["regions_of_interest"],
            "additionalProperties": false,
            "properties": {
              "whole_slide_imaging_file": {
                "$comment": "Digital slide produced from the scanning of conventional glass slides.",
                "$ref": "artifacts/artifact_image.json"
              },
              "roi_annotations": {
                "$comment": "Text describing region of interest for experiment.",
                "$ref": "artifacts/artifact_text.json"
              },
              "mif_output_summary": {
                "$comment": "Summary of the results of the experiment.",
                "$ref": "artifacts/artifact_csv.json"
              },
              "regions_of_interest": {
                "type": "array",
                "mergeStrategy": "arrayMergeById",
                "mergeOptions": { "idRef": "roi_id" },
                "items": {
                  "description": "A region of interest (ROI) is a portion of an image which has been analyzed using image processing software.",
                  "allOf": [
                    { "$ref": "assays/components/composite_image.json" }
                  ],
                  "required": [
                    "roi_id",
                    "im3",
                    "exports"
                  ],
                  "additionalProperties": false,
                  "properties": {
                    "roi_id": {
                      "description": "Identifier of a region of interest within one mIF slide, e.g. 1, 2, 3 or [123 x 321]",
                      "type": "string"
                    },
                    "im3": { "$ref": "assays/components/composite_image.json#properties/im3" },
                    "component_data":{ "$ref": "assays/components/composite_image.json#properties/component_data" },
                    "composite_image":{ "$ref": "assays/components/composite_image.json#properties/composite_image" },
                    "exports": {
                      "type": "array",
                      "mergeStrategy": "arrayMergeById",
                      "mergeOptions": { "idRef": "export_id" },
                      "items": {
                        "description": "An analysis export from inForm of a region of interest (ROI).",
                        "type": "object",
                        "allOf": [
                          { "$ref": "assays/components/mapping.json" }
                        ],
                        "required": [
                          "export_id",
                          "cell_seg_data",
                          "cell_seg_data_summary"
                        ],
                        "additionalProperties": false,
                        "properties": {
                          "export_id": {
                            "description": "Name used for an inForm export of a region of interest within one mIF slide, e.g. CD8, CD45RO",
                            "type": "string"
                          },
                          "cell_seg_data": { "$ref": "assays/components/mapping.json#properties/cell_seg_data" },
                          "cell_seg_data_summary": { "$ref": "assays/components/mapping.json#properties/cell_seg_data_summary" },
                          "phenotype_map": { "$ref": "assays/components/mapping.json#properties/phenotype_map" },
                          "score_data": { "$ref": "assays/components/mapping.json#properties/score_data" },
                          "tissue_seg_data": { "$ref": "assays/components/mapping.json#properties/tissue_seg_data" },
                          "tissue_seg_data_summary": { "$ref": "assays/components/mapping.json#properties/tissue_seg_data_summary" },
                          "binary_seg_maps": { "$ref": "assays/components/mapping.json#properties/binary_seg_maps" },

                          "image_with_all_seg": { "$ref": "assays/components/mapping.json#properties/seg_maps" },
                          "image_with_cell_seg_map": { "$ref": "assays/components/mapping.json#properties/seg_maps" },
                          "image_with_phenotype_map": { "$ref": "assays/components/mapping.json#properties/phenotype_map" },
                          "image_with_tissue_seg": { "$ref": "assays/components/mapping.json#properties/seg_maps" }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/wes/pair_metrics.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "pair_metrics",
  "title": "WES Pair Metrics Files",
  "type": "object",
  "description": "Pair-level metrics for WES.",
  "additionalProperties": false,
  "properties": {
        "all_summaries": {
          "$ref": "artifacts/artifact_text.json"
        }
  },
  "required": ["all_summaries"]
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/rna/rnaseq_level1_analysis.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "rnaseq_level1_analysis",
  "title": "RNAseq Level 1 Sample Analysis Output Files",
  "type": "object",
  "description": "RNAseq assay output files for a sample level 1 analysis.",
  "additionalProperties": false,
  "properties": {
    "cimac_id": {
        "$comment": "Id of a sample within this clinical trial, that this record is based upon.",
        "$ref": "sample.json#properties/cimac_id"
    },
    "star": {
      "$ref": "assays/components/ngs/rna/star.json"
    },
    "rseqc": {
      "$ref": "assays/components/ngs/rna/rseqc.json"
    },
    "salmon": {
      "$ref": "assays/components/ngs/rna/salmon.json"
    }
  },
  "required": [
    "cimac_id",
    "star",
    "rseqc",
    "salmon"
  ]
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/analyses/tcr_analysis.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "tcr_analysis",
    "title": "TCR Output Files",
    "description": "Output files generated from the TCRseq assay: TRA and TRB clones",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "batches": {
            "type": "array",
            "mergeStrategy": "arrayMergeById",
            "mergeOptions": {
                "idRef": "/batch_id"
            },

            "items": {
                "description": "Output files generated from the TCRseq assay: TRA and TRB clones",
                "type": "object",
                "additionalProperties": false,

                "properties": {
                    "batch_id": {
                        "$ref": "assays/tcr_assay.json#properties/batch_id"
                    },
                    "report_trial": {
                        "$ref": "artifacts/artifact_gz.json"
                    },
                    "summary_info": {
                        "$ref": "artifacts/artifact_csv.json"
                    },
                    "records": {
                        "type": "array",
                        "mergeStrategy": "arrayMergeById",
                        "mergeOptions": {
                            "idRef": "/cimac_id"
                        },
                        "items": {
                            "description": "Output files generated from the TCRseq assay: TRA and TRB clones",
                            "type": "object",
                            "additionalProperties": false,

                            "properties": {
                                "cimac_id": {
                                    "$comment": "Id of a sample within this clinical trial, that this record is based upon.",
                                    "$ref": "sample.json#properties/cimac_id"
                                },
                                "tra_clone": {
                                    "$ref": "artifacts/artifact_csv.json"
                                },
                                "trb_clone": {
                                    "$ref": "artifacts/artifact_csv.json"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/imaging/hande_input.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "hande_input",
    "title": "H & E Input Files",
    "type": "object",
    "description": "H & E assay input/output files.",
    "additionalProperties": false,
    "properties": {
      "image_file": {
        "$comment": "Path to the H & E image in SVS format.",
        "$ref": "artifacts/artifact_image.json"
      }
    },
    "required": ["image_file"]
  }

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/ctdna_assay.json
{
	"$schema": "metaschema/strict_meta_schema.json#",
	"$id": "ctdna_assay",
	"title": "Circulating Tumor DNA Assay.",
	"allOf": [{ "$ref": "assays/components/assay_core.json" }],

	"definitions": {
		"entry": {
			"type": "object",
			"mergeStrategy": "objectMerge",
			"description": "A single data record from ctDNA assay.",
			"additionalProperties": false,
			"required": [
				"cimac_id",
				"demultiplexed_bam",
				"demultiplexed_bam_index"
			],
			"properties": {
				"cimac_id": {"$ref": "assays/components/ngs/ngs_assay_record.json#properties/cimac_id"},
				"demultiplexed_bam": {
				  "$ref": "artifacts/artifact_bam.json"
				},
				"demultiplexed_bam_index": {
				  "$ref": "artifacts/artifact_bam_bai.json"
				}
			}
		}
	},
	
	"type": "object",
    "mergeStrategy": "objectMerge",
	"additionalProperties": false,
	"required": [
		"assay_creator",
		"batch_id",
		"records"
	],
	"properties": {
		"assay_creator": {"$ref": "assays/components/assay_core.json#properties/assay_creator"},
		"batch_id": {
            "description": "ctDNA batch identification number. Unique to every batch.",
            "type": "string"
        },
		"records": {
			"type": "array",
			"description": "A single data record from ctDNA assay.",
			"items": {
				"$ref": "assays/ctdna_assay.json#definitions/entry"
			},
			"mergeStrategy": "append"
		}
	}
}
