=== CIMAC-CIDC/cidc-schemas/cidc_schemas/metaschema/strict_meta_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "strict_meta_schema",
  "title": "Strict meta-schema",
  "type": ["object", "boolean"],
  "oneOf": [
    { "required": ["$ref"] },
    { "required": ["const"] },
    {
      "not": {
        "$comment": "this makes additionalProperties or inheritableBase required only for object-describing schemas",
        "anyOf": [
          {
            "properties": {
              "type": {
                "const": "object"
              }
            }
          },
          { "required": ["properties"] }
        ]
      }
    },
    {
      "type": "object",
      "required": ["additionalProperties"],
      "not": {
        "required": ["inheritableBase"],
        "$comment": "'not' disallows matching this, making additionalProperties and inheritableBase mutually exclusive"
      }
    },
    {
      "type": "object",
      "not": {
        "required": ["additionalProperties"],
        "$comment": "'not' disallows matching this, making additionalProperties and inheritableBase mutually exclusive"
      },
      "required": ["inheritableBase"]
    }
  ],
  "properties": {
    "additionalProperties": {
      "$comment": "overrides draft-07 definition",
      "enum": [
          false,
          true
      ]
    },
    "inheritableBase": {
      "$comment": "Shows that a schema is an extensible 'abstract base' to inherit from and doesn't have `additionalProperties` set to false. No end user objects should be of that schema, only of something 'descendant' from it.",
      "const": true
    },
    "example": {
      "type": "string"
    },
    "in_doc_ref_pattern": {
      "$comment": "used in prism custom validator for in doc refs integrity",
      "type": "string"
    },

    "mergeStrategy": { "$comment": "jsonmerge specific" },
    "mergeOptions": { "$comment": "jsonmerge specific" },

    "$schema": {
      "$comment": "overrides draft-07 definition to point to this strict schema",
      "const": "metaschema/strict_meta_schema.json#"
    },
    "additionalItems": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "$ref": "#"
    },
    "items": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "$ref": "#"
    },
    "definitions": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": { "$ref": "#" }
    },
    "properties": {
      "type": "object",
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": { "$ref": "#" }
    },
    "patternProperties": false,
    "dependencies": {
      "type": "object",
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "additionalProperties": {
        "anyOf": [
          { "$ref": "#" },
          {
            "$ref": "#/definitions/stringArray"
          }
        ]
      }
    },

    "$id": {
      "type": "string",
      "format": "uri-reference"
    },
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "$ref": {
      "type": "string",
      "format": "uri-reference"
    },
    "$comment": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "default": true,
    "readOnly": {
      "type": "boolean",
      "default": false
    },
    "examples": {
      "type": "array",
      "items": true
    },
    "multipleOf": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "maximum": {
      "type": "number"
    },
    "exclusiveMaximum": {
      "type": "number"
    },
    "minimum": {
      "type": "number"
    },
    "exclusiveMinimum": {
      "type": "number"
    },
    "maxLength": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minLength": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "pattern": {
      "type": "string",
      "format": "regex"
    },
    "maxItems": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minItems": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "uniqueItems": {
      "type": "boolean",
      "default": false
    },
    "contains": { "$ref": "#" },
    "maxProperties": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeInteger"
    },
    "minProperties": {
      "$ref": "http://json-schema.org/draft-07/schema#/definitions/nonNegativeIntegerDefault0"
    },
    "required": {
      "$ref": "#/definitions/stringArray"
    },
    "propertyNames": { "$ref": "#" },
    "const": true,
    "enum": {
      "type": "array",
      "items": true
    },
    "type": {
      "anyOf": [
        {
          "$ref": "#/definitions/simpleTypes"
        },
        {
          "type": "array",
          "items": {
            "$ref": "#/definitions/simpleTypes"
          },
          "minItems": 1,
          "uniqueItems": true
        }
      ]
    },
    "encrypt": {
      "type": "boolean",
      "default": false
    },
    "format": { "type": "string" },
    "contentMediaType": { "type": "string" },
    "contentEncoding": { "type": "string" },

    "if": { "$ref": "#" },
    "then": { "$ref": "http://json-schema.org/draft-07/schema#" },
    "else": { "$ref": "#" },
    "allOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "anyOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "oneOf": {
      "$ref": "#/definitions/schemaArray"
    },
    "not": { "$ref": "#" }
  },
  "definitions": {
    "schemaArray": {
      "$comment": "overrides draft-07 definition to make self ref link point to this strict schema",
      "type": "array",
      "minItems": 1,
      "items": {
        "anyOf": [
          {"$ref": "#"},
          {"$ref": "http://json-schema.org/draft-07/schema#"}
        ]
      }
    },
    "stringArray": {
      "type": "array",
      "items": { "type": "string" }
    },
    "simpleTypes": { "$ref": "http://json-schema.org/draft-07/schema#/definitions/simpleTypes" }
  },
  "additionalProperties": false
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/wes_tumor_only_analysis.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "wes_tumor_only_analysis",
  "title": "WES tumor-only analysis combined files",
  "type": "object",
  "description": "Combined analysis files for the whole WES assay.",

  "definitions": {
    "sample_analysis": {
      "type": "object",
      "description": "Whole Exome Sequencing assay output files for a tumor normal pair of samples.",

      "required": [
        "run_id",
        "somatic",
        "report",
        "neoantigen",
        "copynumber",
        "msisensor",
        "tumor"
      ],
      "additionalProperties": false,
      "properties": {
        "run_id": {
          "type": "string",
          "description": "An id used as if this was a paired analysis run."
        },
        "somatic": { "$ref": "assays/wes_core.json#definitions/somatic" },
        "report": { "$ref": "assays/wes_core.json#definitions/report" },
        "neoantigen": { "$ref": "assays/wes_core.json#definitions/neoantigen" },
        "copynumber": { "$ref": "assays/wes_core.json#definitions/copynumber" },
        "msisensor": { "$ref": "assays/wes_core.json#definitions/msisensor" },
        "rna": { "$ref": "assays/wes_core.json#definitions/rna" },
        "error": { "$ref": "assays/wes_core.json#properties/error" },

        "tumor": { "$ref": "assays/wes_assay.json#definitions/sample_analysis" },
        "comments": {
          "type": "string",
          "description": "Comments on the tumor-only analysis run."
        }
      }
    }
  },

  "required": [],
  "additionalProperties": false,
  "properties": {
    "runs": {
      "type": "array",
      "items": {
        "$ref": "assays/wes_tumor_only_analysis.json#definitions/sample_analysis"
      },
      "mergeStrategy": "arrayMergeById",
      "mergeOptions": {
        "$comment": "TODO fix to merge by a pair of normal and tumor ids. It requires improvements to the merge strategy code.",
        "idRef": "/run_id"
      }
    },
    "excluded_samples": {
      "$ref": "assays/components/excluded_samples.json"
    }
  }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/tcr/tcr_replicates.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "tcr_input",
  "description": "TCRseq replicate of interest.",
  "additionalProperties": false,
  "allOf": [
    { "$ref": "assays/components/reads_with_index.json"}
  ],
  "properties": {
    "r1": {"$ref": "assays/components/reads_with_index.json#properties/r1"},
    "r2": {"$ref": "assays/components/reads_with_index.json#properties/r2"},
    "i1": {"$ref": "assays/components/reads_with_index.json#properties/i1"},
    "i2": {"$ref": "assays/components/reads_with_index.json#properties/i2"},
    "replicate_no": {
      "description": "Replicate number.",
      "type": "number"
    },
    "rna_quantity_ng": {
      "description": "RNA quantity (in ng).",
      "type": "number"
    }
  },
  "required": [
    "replicate_no",
    "rna_quantity_ng"
  ],
  "mergeStrategy": "objectMerge"
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/tcr/tcr_batch.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "tcr_single_analysis",
    "title": "TCR Output Files",
    "description": "Output files generated from the TCRseq assay: TRA and TRB clones",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "batch id": {
            "$ref": "assays/tcr_assay.json#properties/batch_id"
        },
        "report_trial": {
            "$ref": "artifacts/artifact_gz.json"
        },
        "summary_info": {
            "$ref": "artifacts/artifact_csv.json"
        },
        "records": {
            "type": "array",
            "items": {
                "$ref": "assays/components/ngs/tcr/tcr_pair_analysis.json"
            },
            "mergeStrategy": "arrayMergeById",
            "mergeOptions": {
                "idRef": "/cimac_id"
            }
        }
    }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/mif_antibody.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "mif_antibody",
  "title": "mIF antibody",
  "description": "Data specific to antibody preparation on the multiplex immunofluorescence platform.",
  "additionalProperties": false,
  "type": "object",
  "allOf": [{ "$ref": "assays/components/antibody.json" }],
  "properties": {
    "fluor_wavelength": {
      "description": "Wavelength registered for Alexa Fluor processing.",
      "type": "number"
    },
    "primary_ab_dilution": {
      "description": "Concentration ratio for primary antibody dilution.",
      "type": "string"
    },
    "dilutent": {
      "description": "Dilution agent used for antibody sample.",
      "type": "string"
    },
    "fluor_dilution": {
      "description": "Concentration ratio for fluor dilution agent.",
      "type": "string"
    },
    "antigen_retrieval_time": {
      "description": "Length of time needed for antigen retrieval.",
      "type": "string",
      "format": "time"
    },
    "primary_incubation_time": {
      "description": "Length of time for primary antibody incubation.",
      "type": "string",
      "format": "time"
    },
    "amplification_time": {
      "description": "Length of time required for amplified signal detection.",
      "type": "string",
      "format": "time"
    }
  },
  "required": [
    "fluor_wavelength",
    "primary_ab_dilution",
    "dilutent",
    "fluor_dilution",
    "antigen_retrieval_time",
    "primary_incubation_time",
    "amplification_time"
  ]
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/tcr/tcr_analysis.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "tcr_analysis",
    "title": "TCR Output Files",
    "description": "Output files generated from the TCRseq assay: TRA and TRB clones",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "tca_clone": {
            "$ref": "artifacts/artifact_csv.json"
        },
        "trb_clone": {
            "$ref": "artifacts/artifact_csv.json"
        }
    }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/missing_samples.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "ngs_missing_samples",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": ["cimac_id", "missing_reason"],
    "properties": {
      "cimac_id": {
        "$ref": "sample.json#properties/cimac_id"
      },
      "missing_reason": {
        "type": "string",
        "description": "A comment describing why this sample is missing from the pipeline output."
      }
    }
  },
  "mergeStrategy": "arrayMergeById",
  "mergeOptions": { "idRef": "/cimac_id" }
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/components/ngs/wes/neoantigen.json
{
  "$schema": "metaschema/strict_meta_schema.json#",
  "$id": "neoantigen",
  "title": "WES Neoantigen Output Files",
  "type": "object",
  "description": "Neoantigen output files.",
  "properties": {
    "mhc_class_I_epitopes": {
      "$ref": "artifacts/artifact_tsv.json"
    },
    "mhc_class_II_epitopes": {
      "$ref": "artifacts/artifact_tsv.json"
    },
    "mhc_class_I_filtered_condensed_ranked": {
      "$ref": "artifacts/artifact_tsv.json"
    },
    "mhc_class_II_filtered_condensed_ranked": {
      "$ref": "artifacts/artifact_tsv.json"
    }
  },
  "required": [
    "mhc_class_I_epitopes",
    "mhc_class_I_filtered_condensed_ranked",
    "mhc_class_II_epitopes",
    "mhc_class_II_filtered_condensed_ranked"
  ],
  "additionalProperties": false
}

=== CIMAC-CIDC/cidc-schemas/cidc_schemas/schemas/assays/cytof_e4412_assay.json
{
    "$schema": "metaschema/strict_meta_schema.json#",
    "$id": "cytof_e4412",
    "title": "CYTOF Run",
    "type": "object",
    "description": "Information about the acquisition and analysis CyTOF data for E4412 and similarly formatted trials.",
    "additionalProperties": false,
    "mergeStrategy": "objectMerge",
    "allOf": [
        { "$ref": "assays/cytof_assay_core.json"}
    ],
    "required": ["assay_creator", "batch_id", "records"],
    "properties": {
        "assay_creator": {"$ref": "assays/components/assay_core.json#properties/assay_creator"},
        "assay_run_id": {"$ref": "assays/cytof_assay_core.json#properties/assay_run_id"},
        "cytof_antibodies": {"$ref": "assays/cytof_assay_core.json#properties/cytof_antibodies"},
        "batch_id": {"$ref": "assays/cytof_assay_core.json#properties/batch_id"},
        "acquisition_buffer": {
            "description": "Cell staining buffer used for antibody and cell dilution.",
            "type": "string"
        },
        "debarcoding_protocol": {
            "description": "The strategy/kit used to barcode CyTOF samples, if any",
            "type": "string"
        },
        "source_fcs": {
            "type": "array",
            "items": {
                "$ref": "artifacts/artifact_fcs.json"
            }
        },
        "astrolabe_reports": {
            "$ref": "artifacts/artifact_zip.json"
        },
        "astrolabe_analysis": {
            "$ref": "artifacts/artifact_zip.json"
        },
        "participants": {
            "type": "array",
            "description": "A single data record from CyTOF assay batch.",
            "items": {
                "$ref": "assays/components/cytof/cytof_participant.json"
            },
            "mergeStrategy": "arrayMergeById",
            "mergeOptions": {
              "idRef": "cimac_participant_id"
            }
        }
    }
}
